export const graphData = {
  nodes: [
    { id: 'GrandFather', showChildren: true, show: true, group: 1 },
    { id: 'Father1', showChildren: true, show: true, group: 2 },
    { id: 'Father2', showChildren: true, show: true, group: 2 },
    { id: 'Father3', showChildren: true, show: true, group: 2 },
    { id: 'Father4', showChildren: true, show: true, group: 2 },
    { id: 'Father5', showChildren: true, show: true, group: 2 },
    { id: 'Father6', showChildren: true, show: true, group: 2 },
    { id: 'Father7', showChildren: true, show: true, group: 2 },
    { id: 'Father8', showChildren: true, show: true, group: 2 },
    { id: 'Son1', showChildren: true, show: true, group: 3 },
    { id: 'Son2', showChildren: true, show: true, group: 3 },
    { id: 'Son3', showChildren: true, show: true, group: 3 },
    { id: 'Son4', showChildren: true, show: true, group: 3 },
    { id: 'Son5', showChildren: true, show: true, group: 3 },
    { id: 'Son6', showChildren: true, show: true, group: 3 },
    { id: 'Son7', showChildren: true, show: true, group: 3 },
    { id: 'Son8', showChildren: true, show: true, group: 3 },
    { id: 'Son9', showChildren: true, show: true, group: 3 },
    { id: 'Son10', showChildren: true, show: true, group: 3 },
    { id: 'Son11', showChildren: true, show: true, group: 3 },
    { id: 'Son12', showChildren: true, show: true, group: 3 },
    { id: 'Son13', showChildren: true, show: true, group: 3 },
    { id: 'Son14', showChildren: true, show: true, group: 3 },
    { id: 'Son15', showChildren: true, show: true, group: 3 },
    { id: 'Son16', showChildren: true, show: true, group: 3 },
  ],
  links: [
    { source: 'GrandFather', show: true, target: 'Father1', value: 5 },
    { source: 'GrandFather', show: true, target: 'Father2', value: 5 },
    { source: 'GrandFather', show: true, target: 'Father3', value: 5 },
    { source: 'GrandFather', show: true, target: 'Father4', value: 5 },
    { source: 'GrandFather', show: true, target: 'Father5', value: 5 },
    { source: 'GrandFather', show: true, target: 'Father6', value: 5 },
    { source: 'GrandFather', show: true, target: 'Father7', value: 5 },
    { source: 'GrandFather', show: true, target: 'Father8', value: 5 },
    { source: 'Father1', show: true, target: 'Son1', value: 12 },
    { source: 'Father1', show: true, target: 'Son3', value: 12 },
    { source: 'Father2', show: true, target: 'Son2', value: 9 },
    { source: 'Father2', show: true, target: 'Son4', value: 3 },
    { source: 'Father3', show: true, target: 'Son5', value: 3 },
    { source: 'Father3', show: true, target: 'Son7', value: 3 },
    { source: 'Father4', show: true, target: 'Son6', value: 3 },
    { source: 'Father4', show: true, target: 'Son8', value: 3 },
    { source: 'Father5', show: true, target: 'Son9', value: 3 },
    { source: 'Father5', show: true, target: 'Son10', value: 3 },
    { source: 'Father6', show: true, target: 'Son11', value: 3 },
    { source: 'Father6', show: true, target: 'Son12', value: 3 },
    { source: 'Father7', show: true, target: 'Son13', value: 3 },
    { source: 'Father7', show: true, target: 'Son14', value: 3 },
    { source: 'Father8', show: true, target: 'Son15', value: 3 },
    { source: 'Father8', show: true, target: 'Son16', value: 3 },
  ],
}
